name: slackbot_ci

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: jetdante/slack-audit-bot


jobs:
  build-docker:
    name: Build docker image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from Git tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Git tag version is $VERSION"

      - name: Build&Push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Success message
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "🐳 Image: ${{ env.VERSION }}:latest"